# TODO: Add publication DOIs here. Example format:
# - id: doi:10.xxxx/xxxxx
#   image: https://...
#   tags:
#     - consumer behavior
#
# Publications include works in: Marketing Science, Management Science,
# Journal of Marketing Research, Journal of Marketing.
# Specific DOIs not listed on the website — please add manually.
